# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'mobile' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for mobile

  target 'mobile-tvOSTests' do
    inherit! :search_paths
    # Pods for testing

    pod 'react-native-webview', :path => '../node_modules/react-native-webview'

  end

  target 'mobileTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
