export const WIRED_SCREENSHARE_SET_DEVICE_LABEL
    = 'WIRED_SCREENSHARE_SET_DEVICE_LABEL';

export const WIRED_SCREENSHARE_SET_IDLE_VALUE
    = 'WIRED_SCREENSHARE_SET_IDLE_VALUE';

export const WIRED_SCREENSHARE_SET_DEVICE_CONNECTED
    = 'WIRED_SCREENSHARE_SET_DEVICE_CONNECTED';
