export {
    ArrowForward,
    Backspace,
    CalendarToday,
    Call,
    CallEnd,
    Dialpad,
    ExpandLess,
    ExpandMore,
    Feedback,
    GridOff,
    GridOn,
    HelpOutline,
    HighlightOff,
    KeyboardArrowDown,
    Mic,
    MicOff,
    MoreVert,
    PersonAdd,
    ScreenShare,
    Search,
    Settings,
    Star,
    StarBorder,
    Videocam,
    VideocamOff,
    VolumeUp
} from '@material-ui/icons';
export { default as WiredScreenshare } from './wired-screenshare-icon';
export { default as WirelessScreenshare } from './wireless-screenshare-icon';
