export const HANG_UP = 'HANG_UP';

export const REMOTE_CONTROL_REQUEST_STATE = 'REMOTE_CONTROL_REQUEST_STATE';

export const REMOTE_CONTROL_UPDATE_SCREENSHARE_STATE = 'REMOTE_CONTROL_UPDATE_SCREENSHARE_STATE';
