platform :ios, '10.0'

workspace 'spot-controller'

target 'spot-controller' do
  project 'spot-controller.xcodeproj'

  pod 'React', :path => '../node_modules/react-native', :subspecs => [
      'Core',
          'CxxBridge',
          'DevSupport',
          'RCTText',
          'RCTImage',
          'RCTNetwork',
          'RCTWebSocket',
          'RCTSettings',
          'RCTAnimation',
          'RCTLinkingIOS',
      ]

  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod "yoga", :path => "../node_modules/react-native/ReactCommon/yoga"

  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'
  pod 'RNSVG', :path => '../node_modules/react-native-svg'
  pod 'ReactNativeBeaconsManager', :path => '../node_modules/react-native-beacons-manager'
  pod 'react-native-keep-awake', :path => '../node_modules/react-native-keep-awake'
  pod 'react-native-webview', :path => '../node_modules/react-native-webview'
  

end
