export const REMOTE_CONTROL_SET_JOIN_CODE = 'REMOTE_CONTROL_SET_JOIN_CODE';

export const REMOTE_CONTROL_SET_LOCK = 'REMOTE_CONTROL_SET_LOCK';

export const REMOTE_CONTROL_SET_MEETING = 'REMOTE_CONTROL_SET_MEETING';

export const REMOTE_CONTROL_SET_ROOM_NAME = 'REMOTE_CONTROL_SET_ROOM_NAME';

export const REMOTE_CONTROL_SET_SPOT_STATE = 'REMOTE_CONTROL_SET_SPOT_STATE';

export const REMOTE_CONTROL_SPOT_LEFT = 'REMOTE_CONTROL_SPOT_LEFT';
