export const SETUP_COMPLETED = 'SETUP_COMPLETED';

export const SET_AVATAR_URL = 'SET_AVATAR_URL';

export const SET_DISPLAY_NAME = 'SET_DISPLAY_NAME';

export const SET_IS_SPOT = 'SET_IS_SPOT';

export const SET_SHOW_MEETING_TOOLBAR = 'SET_SHOW_MEETING_TOOLBAR';
