export const SPOT_TV_CLEAR_STATE = 'SPOT_TV_CLEAR_STATE';

export const SPOT_TV_SET_JOIN_CODE = 'SPOT_TV_SET_JOIN_CODE';

export const SPOT_TV_SET_MUC_LOCK = 'SPOT_TV_SET_MUC_LOCK';

export const SPOT_TV_SET_MUC_ROOM = 'SPOT_TV_SET_MUC_ROOM';

export const SPOT_TV_SET_STATE = 'SPOT_TV_SET_STATE';
