name: 'CI'
on: [pull_request]
jobs:
    lint-spot-client:
        name: Lint [spot-client]
        runs-on: ubuntu-latest

        steps:
            - name: Step 1 - checkout
              uses: actions/checkout@v3

            - name: cd spot-client
              run: cd spot-client

            - name: Step 2 - setup node 16
              uses: actions/setup-node@v3
              with:
                  node-version: 16
                  cache: 'npm'
                  cache-dependency-path: spot-client/package-lock.json

            - name: Step 3 - run install
              working-directory: 'spot-client'
              run: npm install

            - name: Step 4 - run lint
              working-directory: 'spot-client'
              run: npm run lint

    e2e:
        name: Run e2e spot webdriver
        runs-on: macos-latest

        steps:
            - name: Step 1 - info
              run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event, running on ${{ runner.os}}, branch name ${{ github.ref}}, ."

            - name: Step 2 - checkout
              uses: actions/checkout@v3

            - name: Step 3 - run install [spot-client]
              working-directory: spot-client
              run: npm install

            - name: Step 4 - run install [spot-webdriver]
              working-directory: spot-webdriver
              run: npm install

            - name: Step 5 - run tests [spot-webdriver]
              working-directory: spot-webdriver
              run: npm run ci