name: 'CI - spot-electron'
on: [pull_request]
jobs:
    build-spot-electron-mac:
        name: Build on macOS
        runs-on: macOS-latest

        steps:
            - name: Step 1 - checkout
              uses: actions/checkout@v4

            - name: Step 2 - setup node
              uses: actions/setup-node@v4
              with:
                node-version-file: '.nvmrc'

            - name: Step 3 - run install
              working-directory: 'spot-electron'
              run: npm install

            - name: Step 4 - build
              working-directory: 'spot-electron'
              run: npm run dist

    build-spot-electron-windows:
        name: Build on Windows
        runs-on: windows-latest

        steps:
            - name: Step 1 - checkout
              uses: actions/checkout@v4

            - name: Step 2 - setup node
              uses: actions/setup-node@v4
              with:
                node-version-file: '.nvmrc'

            - name: Step 3 - run install
              working-directory: 'spot-electron'
              run: npm install

            - name: Step 4 - build
              working-directory: 'spot-electron'
              run: npm run dist

    unit-tests-spot-electron:
        name: Unit-tests
        runs-on: ubuntu-latest

        steps:
            - name: Step 1 - checkout
              uses: actions/checkout@v4

            - name: Step 2 - setup node
              uses: actions/setup-node@v4
              with:
                node-version-file: '.nvmrc'

            - name: Step 3 - run install
              working-directory: 'spot-electron'
              run: npm install

            - name: Step 4 - run lint
              working-directory: 'spot-electron'
              run: npm run lint

            - name: Step 5 - run test
              working-directory: 'spot-electron'
              run: npm run test
