name: 'CI - spot-client'
on: [pull_request]
jobs:
    test-spot-client:
        name: Unit-tests
        runs-on: ubuntu-latest

        steps:
            - name: Step 1 - checkout
              uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4

            - name: Step 2 - setup node
              uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020  # v4
              with:
                node-version-file: '.nvmrc'

            - name: Step 3 - run install
              working-directory: 'spot-client'
              run: npm install

            - name: Step 4 - run lint
              working-directory: 'spot-client'
              run: npm run lint

            - name: Step 5 - run test
              working-directory: 'spot-client'
              run: npm run test

    e2e:
        name: E2E tests
        runs-on: macos-13

        steps:
            - name: Step 1 - info
              run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event, running on ${{ runner.os}}, branch name ${{ github.ref}}, ."

            - name: Step 2 - checkout
              uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5  # v4

            - name: Step 3 - setup node
              uses: actions/setup-node@49933ea5288caeca8642d1e84afbd3f7d6820020  # v4
              with:
                node-version-file: '.nvmrc'

            - name: Step 4 - run install [spot-client]
              working-directory: spot-client
              run: npm install

            - name: Step 5 - run install [spot-webdriver]
              working-directory: spot-webdriver
              run: npm install

            - name: Step 6 - run tests [spot-webdriver]
              working-directory: spot-webdriver
              run: npm run ci

            - name: Step 7 - Archive Test Results
              if: always()
              uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02  # v4
              with:
                name: webdriver-results
                path: spot-webdriver/webdriver-results/
